### ISSUE TITLE
Python 2.7 SyntaxError

### ISSUE THREAD

**Issue by abivolmv** [aws/aws-xray-sdk-python#102]
I get this error when running a local script with python 2.7.15 on Windows :

```
python run_surreal.py
Traceback (most recent call last):
  File "run_surreal.py", line 19, in <module>
    from surreal.surreal import SQSController
  File "C:\Users\xxx\repos\surreal-queue-dispatcher\surreal\surreal.py", line 20, in <module>
    from aws_xray_sdk.core.async_context import AsyncContext
  File "C:\Users\xxx\repos\surreal-queue-dispatcher\venv\lib\site-packages\aws_xray_sdk\core\async_context.py", line 14
    def __init__(self, *args, loop=None, use_task_factory=True, **kwargs):
                                 ^
SyntaxError: invalid syntax
```
I guess this line is not python 2.x compatible :
https://github.com/aws/aws-xray-sdk-python/blob/master/aws_xray_sdk/core/async_context.py#L14

**Comment by abivolmv** [comment]
AsyncContext also uses asyncio which is not compatible with python 2.x . So the question : Is this sdk compatible with python 2.x ? In the readme it says it is.

**Comment by haotianw465** [comment]
Hi, the SDK only imports `async` related modules if python version >= 3.5. You can find the relevant lines here:
 https://github.com/aws/aws-xray-sdk-python/blob/master/aws_xray_sdk/core/__init__.py
https://github.com/aws/aws-xray-sdk-python/blob/master/aws_xray_sdk/core/utils/compat.py

Do you have the full stack trace or the code snippet of how you are importing the SDK so I can take a further look?

**Comment by abivolmv** [comment]
Hi, I was doing the following :

`xray_recorder.configure(service='my_service', context=AsyncContext())`

I am trying to trace a call made through twisted's defer in a custom script (not Lambda etc).

```
subsegment = xray_recorder.begin_subsegment('xxx')
def callbackBar():
       #I want to trace this callback with the parent subsegment
deffer = foo()
deffer.addCallbacks(callbackBar)
xray_recorder.end_subsegment()
```

Can't find any docs on how to do that in python2.7 . If it's not possible then pls tell me how would we do it in 3.5.

**Comment by haotianw465** [comment]
Right now async support only works for python 3.5 and later. This unit test for async recorder might give you a good example of how to capture async functions using decorators https://github.com/aws/aws-xray-sdk-python/blob/master/tests/test_async_recorder.py. Please let me know if this answers your question.
