### ISSUE TITLE
Sampling pollers have an issue on Windows OS

### ISSUE THREAD

**Issue by abivolmv** [aws/aws-xray-sdk-python#103]
Hi,

I get the following error when using the sdk :

![xray_sampling_error](https://user-images.githubusercontent.com/39116856/46342286-a9902880-c63a-11e8-8c19-96d35e33f4ac.PNG)

This is the call to sampling rules in case its needed:

![xray_sampling_error1](https://user-images.githubusercontent.com/39116856/46342306-b280fa00-c63a-11e8-9313-6ce6394fa430.PNG)

**Comment by abivolmv** [comment]
Before I got this error :

![image](https://user-images.githubusercontent.com/39116856/46342580-62eefe00-c63b-11e8-93ed-7fd026ef249b.png)

and I applied a patch directly in dateutils like here :
https://stackoverflow.com/a/43688152/2470346

**Comment by haotianw465** [comment]
It seems like a compatibility issue on `botocore` and your OS at first and after applying the patch it triggers another issue in X-Ray SDK.

Do you mind providing which python version are you using, is it 32bit or 64bit and what is your timezone offset in your OS so I can take a further look?

**Comment by abivolmv** [comment]
I tried with Python 2.7 64bit and python 3.7 64bit - same issue. Timezone is UTC+01 (Amsterdam, Berlin)

**Comment by abivolmv** [comment]
I also get this error (Python 3.7 64bit)

![image](https://user-images.githubusercontent.com/39116856/46463161-9197e080-c7c3-11e8-98d7-6901d4a9339a.png)

**Comment by haotianw465** [comment]
This is a bug on the SDK support with Windows platform. The SDK currently uses `strftime` and the character `%s` for conversion from `datetime` to Unix epoch. You can see from http://man7.org/linux/man-pages/man3/strftime.3.html. However, this character doesn't work cross-platform and it is unix specific. The characters work cross-platform can be found here http://strftime.org and `%s` is not one of those.

The SDK needs to choose an implementation of converting `datetime` to POSIX epoch that works cross platforms. We will look into a fix as soon as possible. Sorry for the inconvenience.

**Comment by haotianw465** [comment]
This issue should be fixed in the latest release 2.2.0. If you still have issues, feel free to request for re-open.
