### ISSUE TITLE
Not patching after pyinstaller used

### ISSUE THREAD

**Issue by abivolmv** [aws/aws-xray-sdk-python#106]
Not sure if this belongs here , but if you have some hints ...
So the issue is that after I package the custom script with pyinstaller I don't get the request to aws services in the traces :
![xray_with_pyinstaller](https://user-images.githubusercontent.com/39116856/46681178-f354b200-cbea-11e8-8ecb-70f5a30eee09.JPG)

This is how it looks when I run the script directly (without pyinstaller) :

![xray_without_pyinstaller](https://user-images.githubusercontent.com/39116856/46681206-036c9180-cbeb-11e8-9ebc-971db9b1047d.JPG)

It seems that the libraries are not patched ?
I added the required json from the manifest to the .spec file - didn't help.

```
# -*- mode: python -*-

block_cipher = None

needed_aws_xray_sdk_files = [(r'aws_xray_sdk\core\sampling\local\sampling_rule.json',
                           r'C:\Users\xxxx\repos\surreal-queue-dispatcher\venv\Lib\site-packages\aws_xray_sdk\core\sampling\local\sampling_rule.json',
                          'DATA'),
                          (r'aws_xray_sdk\ext\resources\aws_para_whitelist.json',
                           r'C:\Users\xxxx\repos\surreal-queue-dispatcher\venv\Lib\site-packages\aws_xray_sdk\ext\resources\aws_para_whitelist.json',
                          'DATA')]

patched_dateutil = [(r'dateutil\tz\tz.py',
                           r'C:\Users\xxxx\repos\surreal-queue-dispatcher\venv\Lib\site-packages\dateutil\tz\tz.py',
                          'DATA')]

a = Analysis(['run_surreal.py'],
             pathex=['.', './notifications'],
             binaries=[],
             datas=[
                 ('./notifications/*.pem', './notifications'),
                 ('./notifications/*.key', './notifications'),
                 ('./notifications/*.crt', './notifications')
             ],
             hiddenimports=[],
             hookspath=[],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          exclude_binaries=True,
          name='message_dispatcher',
          debug=False,
          strip=False,
          upx=True,
          console=True )
coll = COLLECT(exe,
               a.binaries,
               needed_aws_xray_sdk_files,
               patched_dateutil,
               a.zipfiles,
               a.datas,
               strip=False,
               upx=True,
               name='message_dispatcher')
```

**Comment by haotianw465** [comment]
Could you configure your log level to debug when running the script? The SDK emits log messages on patching success and failure for each module. It will be helpful to look at those logs. You can see the message strings here https://github.com/aws/aws-xray-sdk-python/blob/master/aws_xray_sdk/core/patcher.py

**Comment by abivolmv** [comment]
Thanks a lot for the hint!
I raised the errors in the pather.py and found out the modules `ext.` are not included. That is because they are not included with normal `import` so pyinstaller doesn't know about them. I then used the hidden-import parameter in the spec file and it worked.
```
hiddenimports=['aws_xray_sdk.ext.botocore']
```
I also moved from patch_all() to patch('botocore',).
