### ISSUE TITLE
Patching sqlalchemy

### ISSUE THREAD

**Issue by zhammer** [aws/aws-xray-sdk-python#124]
Is there a reason we can't just patch out the sqlalchemy `SessionMaker` with the `XRaySessionMaker`?

Curious why this is isolated from the rest of the patching.

**Comment by chanchiem** [comment]
Hey Zhammer,

SQLAlchemy was written through the following pull request: https://github.com/aws/aws-xray-sdk-python/pull/14

And although it looks like it could've been written with the patcher, the current implementation utilized a different design specific to SQLAlchemy's base session and query classes.

**Comment by zhammer** [comment]
I'm using postgres and actually just patched out `psycopg2` which has worked fine for me!

**Comment by chanchiem** [comment]
Closing since you've found a solution to your underlying problem.
