### ISSUE TITLE
Django documentation should mention that defining AWS_XRAY_TRACING_NAME is mandatory

### ISSUE THREAD

**Issue by millarm** [aws/aws-xray-sdk-python#141]
In settings.py you must, at a minimum have

```
XRAY_RECORDER = {
    'AWS_XRAY_TRACING_NAME': 'My application',
}
```

**Comment by chanchiem** [comment]
Hey,

Thank you for creating an issue for this. I'll be happy to help! I believe it is mentioned in our docs: https://docs.aws.amazon.com/xray-sdk-for-python/latest/reference/frameworks.html
> Environment variables have higher precedence over user settings. If neither is set, the defaults values shown previously are used. ‘AWS_XRAY_TRACING_NAME’ is required unless specified as an environment variable. All other keys are optional. For further information on individual settings, see the Configure Global Recorder section.

Are you referring to the README in the Github repository? I'd be happy to add information about that to make it less confusing.

**Comment by millarm** [comment]
Yep, the bit that's potentially misleading is this section:

https://github.com/aws/aws-xray-sdk-python#django

Adding a link to that URL would be nice too.

**Comment by chanchiem** [comment]
Added PR #142
