### ISSUE TITLE
No module named pkg_resources with Serverless Framework

### ISSUE THREAD

**Issue by gcampionpae** [aws/aws-xray-sdk-python#16]
We are deploying our Lambda functions with the Serverless Framework and when we use version .95, our Lambda functions throw this error: 

Unable to import module 'lib/cancel_trial_subscription': No module named pkg_resources

When using version .94, there isn't an issue.  Also, if a deployment is made from a mac instead of through our CI/CD pipeline, which runs on Linux, it's also not an issue.  Any ideas how this could be happening?

**Comment by haotianw465** [comment]
Hi there, sorry for any inconvenience. `pkg_resources` is introduced in this PR https://github.com/aws/aws-xray-sdk-python/pull/6/files#diff-b28c74eefc290d02eb40fd81f4e26b58R5 which added support for async capture and aioboto. Per http://setuptools.readthedocs.io/en/latest/pkg_resources.html it is distributed with `setuptools `. How is your CI/CD setup different than your dev box when packaging and deploying?

**Comment by gcampionpae** [comment]
Both deployments happen from a docker container with the Serverless Framework.  The only real difference would be that when we run the docker container locally it's on a mac and on our gitlab runner it's a linux box.  Otherwise there really isn't much of a difference.

I've also tried following the exact steps locally on my mac as in our CI/CD pipeline and it still works correctly.  

Here is our dockerfile:

`FROM node

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y \
  build-essential \
  python \
  python-dev \
  python-pip \
  curl \
  git-core && \
  rm -rf /var/lib/apt/lists/* && \
  apt-get clean

RUN pip install --upgrade --ignore-installed pip
RUN pip install virtualenv

RUN npm install serverless@1.20.2 -g
RUN npm install --prefix /sls_plugins serverless-python-requirements@2.5.0
RUN npm install --prefix /sls_plugins serverless-plugin-git-variables@2.0.0
RUN npm install --prefix /sls_plugins serverless-plugin-tracing@2.0.0
RUN npm install --prefix /sls_plugins serverless-prune-plugin@1.3.0
RUN npm install aws-sdk@2.101.0 -g

COPY .pydistutils.cfg /root/.pydistutils.cfg
COPY serverless_wrapper /usr/local/bin/serverless_wrapper
RUN chmod a+x /usr/local/bin/serverless_wrapper
COPY setup_ci_environment /usr/local/bin/setup_ci_environment
RUN chmod a+x /usr/local/bin/setup_ci_environment
COPY requirements_adfs.txt /root/requirements_adfs.txt
RUN mv /root/.pydistutils.cfg /root/.pydistutils.cfg_old && \
    pip install -r /root/requirements_adfs.txt && \
    rm -f /root/requirements_adfs.txt && \
    mv /root/.pydistutils.cfg_old /root/.pydistutils.cfg

COPY samlapi_adfs3.py /usr/local/bin/samlapi_adfs3.py
RUN chmod a+x /usr/local/bin/samlapi_adfs3.py

WORKDIR /workspace

CMD ["serverless"]
`

We pull this docker image to the machine and then run the setup ci script which is the following:
`
#!/bin/bash

mv /root/.pydistutils.cfg /root/.pydistutils.cfg_old
virtualenv venv
source venv/bin/activate
pip install -r requirements-dev.txt --quiet
mv /root/.pydistutils.cfg_old /root/.pydistutils.cfg
ln -s -f /sls_plugins/node_modules ./.serverless_plugins
`
from there we just run sls deploy for our staging environment

`Running with gitlab-ci-multi-runner 9.5.0 (413da38)
  on nue-docker-01 (ba60b53f)
Using Docker executor with image serverless-docker-image:serverless-1.20 ...
Using docker image sha256:1bbf0506e176d248a2ee0db39ef78ff9775b0f54a0afb5dded89d7d12155dda3 for predefined container...
Pulling docker image ....serverless-docker-image:serverless-1.20 ...
Using docker image ....serverless-docker-image:serverless-1.20 ID=sha256:ae8671f18ef92124361445893cef52fac9f569ef861ce48887f378b69fb12c55 for build container...
Running on runner-ba60b53f-project-51-concurrent-0 via nue-docker-01...
Fetching changes...
Removing .cache/
Removing .requirements/
Removing .serverless/
Removing .serverless_plugins
Removing lib/__init__.pyc
Removing lib/models/__init__.pyc
Removing lib/models/auth0_service.pyc
Removing lib/models/plan_service.pyc
Removing lib/models/subscription_service.pyc
Removing tests/__init__.pyc
Removing tests/__pycache__/
Removing tests/integration/__init__.pyc
Removing tests/integration/__pycache__/
Removing venv/
HEAD is now at 2102595 Merge branch 'pyup-update-boto3-1.5.4-to-1.5.6' into 'master'
Checking out 748e1d40 as master...
Skipping Git submodules setup
$ source setup_ci_environment
New python executable in /var/gitlab-builds/pod/sls-subscriptions/venv/bin/python
Installing setuptools, pip, wheel...done.
$ sls deploy -s staging
Serverless: Parsing Python requirements.txt
Serverless: Installing required Python packages for runtime python2.7...
Serverless: Linking required Python packages...
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Unlinking required Python packages...
Serverless: Tracing ENABLED for function "sls-subscriptions-staging-get-subscription"
Serverless: Tracing ENABLED for function "sls-subscriptions-staging-create-subscription"
Serverless: Tracing ENABLED for function "sls-subscriptions-staging-list-subscriptions"
Serverless: Tracing ENABLED for function "sls-subscriptions-staging-update-subscription"
Serverless: Tracing ENABLED for function "sls-subscriptions-staging-cancel-subscription"
Serverless: Tracing ENABLED for function "sls-subscriptions-staging-cancelTrialSubscription"
Serverless: Tracing ENABLED for function "sls-subscriptions-staging-syncAuth0CanHaveTrialFlag"
Serverless: Tracing ENABLED for function "sls-subscriptions-staging-list-plans"
Serverless: Tracing ENABLED for function "sls-subscriptions-staging-get-plan"
Serverless: Tracing ENABLED for function "sls-subscriptions-staging-get-estimates"
Serverless: Tracing ENABLED for function "sls-subscriptions-staging-validate-subscription-vat"
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading artifacts...
Serverless: Uploading service .zip file to S3 (2.23 MB)...
Serverless: Validating template...
Serverless: Updating Stack...
Serverless: Checking Stack update progress...
............................................................................
Serverless: Stack update finished...`

**Comment by gcampionpae** [comment]
After looking at it more today, it seems that I must have been deploying from my local computer with version .94 because now no matter what I do, I cannot deploy .95 with serverless and not get this error.

**Comment by haotianw465** [comment]
I'm trying to reproduce this issue. Before that I would like to confirm a few things. Is https://serverless.com the one your are using for deploying to Lambda? Your Lambda runtime is Python2.7 is that correct?

**Comment by gcampionpae** [comment]
yes we are using the Serverless Framework for deploying our functions and are on Version 1.20.  Our runtime is Python2.7.  Thanks for looking into this!!

**Comment by haotianw465** [comment]
Sorry for the delay. I have some findings and I would like to share them with you.

In my mac I first ran `virtualenv -p /usr/bin/python venv` to create the python2.7 environment. Then put my lambda function code and installed all requirements. Then I packaged everything under `venv/lib/python2.7/site-packages` along with my function as a Lambda deployment package, as Lambda official document instructed. The function can run successfully. This is because when I ran command `virtualenv` it will install `pip`, `wheels`, `setuptools` under `venv/lib/python2.7/site-packages`. And the module `pkg_resources` also shows up.

So I repeat the above step but before packaging I explicitly deleted `pkg_resources` and deployed to Lambda. Then I got a similar message "Unable to import module 'main': No module named pkg_resources".

By looking at your CI setup script I don't see any issue. After the following commands
```
virtualenv venv
source venv/bin/activate
pip install -r requirements-dev.txt --quiet
```
you should have everything you need to build your Lambda deployment package.

So the question comes down to how Serverless do packaging when the framework performs packaging. I would suggest two things. First is to download your deployed function code and unzip it. Check if any of the modules installed by `virtualenv` is present. It could be that Serverless omit those modules. The second thing you could do is to add `setuptools` to your `requirements-dev.txt` and see if that module is packaged. Please let me know if that works for you.

On the other side we will look into revert the change on depending on `pkg_resources`  at runtime. It seems like both the contributor and myself overlooked to this new dependency as we take it for granted when developing under a virtual environment.

**Comment by gcampionpae** [comment]
Thanks so much for the help with this!  Including the setuptools package in the requirements did make this work.  I will open an issue with the serverless team to see if this is how it should function or if this is a bug.
