### ISSUE TITLE
Is it possible to make xray_recorder.capture add subsegments recursively?

### ISSUE THREAD

**Issue by rokka-n** [aws/aws-xray-sdk-python#174]
I was looking at readme here
> An xray_recorder.capture() decorator will be applied to all functions and class methods in the given module and all the modules inside them recursively. Some files/modules can be excluded by providing to the patch function a regex that matches them.

and assumed that adding a decorator to entry method would create subsegments for all recursive methods - named after methods. Which is quite handy when looking at traces.

say for something like this snippet below I expected x-ray to have method m2 as a subsegment for whatever setup for m1. However, it records subsegment only for patched libraries in recursive calls. So if m2 has boto method to get an object from s3, it would be recorded.

```
@xray_recorder.capture()
def m1():
  m2()

def m2():
   print('Hola')

m1()
```

Is it feasible to make subsegments recorded automatically after method names?

Thank you!

**Comment by chanchiem** [comment]
Hey,

The documentation snippet that you've provided talks about only the modules that are patched, and not about the internal methods themselves. For example, if `boto3` utilizes the `requests` package (assuming `requests` and `boto3` are patched), a call to `boto3.high_level_that_calls_request` would result in a subsegment tree where the top level would hold the subsegment that represents the `boto3.high_level_that_calls_request` call, and it would contain a child subsegment that represents its internal `requests` call.

Is the request here to make the `recorder.capture` annotation automatically name its subsegment based on the method being annotated, or is it to allow for the `recorder.capture` annotation to recursively capture all subsequent method calls, using the method name as the subsegment name?

**Comment by rokka-n** [comment]
Thank you, it’s for the latter - capture methods as subsegments recursively.

**Comment by luzfcb** [comment]
I'm really curious about how much overhead aws-xray-sdk-python adds when as used in any project and how much this would be increased by automatically recursively creating subsegments.

**Comment by chanchiem** [comment]
Hey,

After further discussion, we don't think this would be the best experience performance-wise. This would provide too big of an overhead as the entire stack trace would then be recorded, which in most cases is not necessary for a single subsegment. If you would like to implement this locally on your own branch for your particular use case, we'd be happy to provide some guidance and support  on how that can be achieved. I'll be closing this for now. Feel free to re-open if you have any objections or want support for implementing it locally.

Thanks!

**Comment by rokka-n** [comment]
I’d like to look into implementation details. Want to run some perf test and then gauge our internal users response of having full or truncated traces.

Thanks!
