### ISSUE TITLE
patch will not work with certain paths

### ISSUE THREAD

**Issue by errietta** [aws/aws-xray-sdk-python#189]
Say I want to patch an external import: "/usr/local/lib/python3.6/site-packages/my_module/"
Because of the `.` in `python3.6`, this line will break the path:
` module = module.replace('.', '/')`

https://github.com/aws/aws-xray-sdk-python/blob/324d18590363a9e926599f15c1aac0368d99d30e/aws_xray_sdk/core/patcher.py#L51

Unless I'm misunderstanding something, I don't understand how this is supposed to work with external modules in general, unless one gives the full path and the path doesn't contain a dot.

**Comment by errietta** [comment]
(I'm an idiot, turns out I don't need it, however I still think maybe the module code seems confused as to what it does and doesn't support re patching imports 😅 )

**Comment by chanchiem** [comment]
Just for clarification, which modules specifically are you trying to patch? Our patcher only supports the patchers that we have implemented for it, so as long as your location contains the package that we provide patchers for, it probably won't work. The supported modules are located in the ext/** folder of the SDK, you will see these implemented patchers.

**Comment by chanchiem** [comment]
I will be closing this issue. If you have any problems, feel free to reopen this issue with any questions.
