### ISSUE TITLE
Fix failing Travis CI

### ISSUE THREAD

**Issue by chanchiem** [aws/aws-xray-sdk-python#195]
After the merge of PR #186, we are noticing segment missing failures. However it most likely is not related the merging of the PR.

After experimentation, it looks like someting's happening with the sqlite3 test suite. This is still under investigation, but perhaps the version of sqlite3 was increased.

**Comment by mikegrima** [comment]
It's most likely related to: https://github.com/nedbat/coveragepy/issues/889

**Comment by chanchiem** [comment]
Thanks for the information! Going to do some investigation to see what change was introduced that caused it to break with X-Ray.

**Comment by chanchiem** [comment]
As a temporary work around for now while we find the root cause, it looks like downgrading `coverage` to `4.5.4` resolves the issue.
