### ISSUE TITLE
subsegment name special characters

### ISSUE THREAD

**Issue by thehesiod** [aws/aws-xray-sdk-python#20]
currently the following is allowed: `string.ascii_letters + string.digits + '_.:/%&#=+\-@ '` per entity.py.  However in the requests module (and httplib module I'm proposing based on it) it uses the url, which can include a `?` character which yields a lot of warnings.  Was the intention that everything after '?' would be stripped off?  If so the requests module isn't doing this either.  Could either do simple string clipping or use something like yarl

**Comment by haotianw465** [comment]
Query string with "?" should not be part of a subsegment name. This is a bug. We will looking into a fix. A PR is also welcome.

**Comment by thehesiod** [comment]
Ok cool, I'll add it to my httplib PR
