### ISSUE TITLE
"failed to send data to X-Ray daemon." -> "Message too long"

### ISSUE THREAD

**Issue by tobiasmcnulty** [aws/aws-xray-sdk-python#201]
We've enabled the `record_full_document` parameter for the pymongo patch method (https://github.com/aws/aws-xray-sdk-python/blob/master/aws_xray_sdk/ext/pymongo/patch.py#L12-L14) and are seeing the below exception when attempting to record a large query/response from mongo.

Would it be possible to update the UDP emitter to truncate the data or split it up so we can see at least some of it in the console?

Many thanks!

```
failed to send data to X-Ray daemon.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aws_xray_sdk/core/emitters/udp_emitter.py", line 63, in _send_data
    self._port))
OSError: [Errno 90] Message too long
```

**Comment by tobiasmcnulty** [comment]
I should add, we're also seeing events with no segments in the console, which is maybe related?

![Screen Shot 2020-01-29 at 12 51 30 PM](https://user-images.githubusercontent.com/160132/73382783-2adee600-4296-11ea-833a-c83c95a4b6cd.png)

(ID has been obfuscated.)

**Comment by awssandra** [comment]
Hi tobiasmcnulty,

I'd suggest using the streaming threshold in the recorder first. The idea is that subsegments can be batched and sent independently of their segment, as long as they're complete. This can help alleviate the UDP size limit when working with large segment documents.

[Relevant Note](https://github.com/aws/aws-xray-sdk-python/blob/d081441dd268532c03813adf21ab85c2c2749659/aws_xray_sdk/core/recorder.py#L127)
[More Notes](https://github.com/aws/aws-xray-sdk-python/blob/d081441dd268532c03813adf21ab85c2c2749659/aws_xray_sdk/core/recorder.py#L130)

We have similar logic on Lambda, where we [force every subsegment to send when complete](https://github.com/aws/aws-xray-sdk-python/blob/d081441dd268532c03813adf21ab85c2c2749659/aws_xray_sdk/core/recorder.py#L60)

So, I'd expect something like the following to work...
`
from aws_xray_sdk.core import xray_recorder

xray_recorder.configure(
    //... configs here
    streaming_threshold=0
    //Magic number here, default is 30. Setting to 0 will force a subsegment to send as soon as it's closed.
)
`

**Comment by dpoirier** [comment]
@awssandra It looks as if the streaming_threshold won't be used unless it's truthy: https://github.com/aws/aws-xray-sdk-python/blob/37e57bb647f98460f5ca3c45f29eb0f44ad4791b/aws_xray_sdk/core/recorder.py#L162

So I wouldn't think setting it to 0 would have any effect. Would setting it to 1 or -1 be almost as good?

This might be a bug - maybe it should be checking if streaming_threshold is not None.

(I work with @tobiasmcnulty.)

**Comment by awssandra** [comment]
Hi dpoirier,

That looks like a bug to me - zero should be an acceptable value (I am most knowledgeable of the Node SDK so [here is the setting logic there](https://github.com/aws/aws-xray-sdk-node/blob/8109e1e256288764571bdad45f2100c48280b8c4/packages/core/lib/segments/segment_utils.js#L37)).

Setting to "1" should work in a very similar fashion.
Feel free to open a PR to correct this, I'll try to get this prioritized on my end.
