### ISSUE TITLE
Is there need in Bottle plugin for xray sdk, I will contribute

### ISSUE THREAD

**Issue by polamayster** [aws/aws-xray-sdk-python#202]
Would you find having Bottle plugin useful, in addition to existing Flask and Django middlewares/extentions, so it would be easier even for a broader auditory of Python projects to integrate/use aws-xray-sdk-python? And if so, I will contribute.

**Comment by bhautikpip** [comment]
Hi @polamayster,

Thanks for the suggestion. I think having bottle plugin will be useful. We would like to review your PR on that.

**Comment by polamayster** [comment]
https://github.com/aws/aws-xray-sdk-python/pull/204
