### ISSUE TITLE
xray sdk with boto patch shouldn't trace itself

### ISSUE THREAD

**Issue by kapilt** [aws/aws-xray-sdk-python#207]
i've done some custom integration for aws xray sdk into a project that also uses boto, when i end the segment, and then try to send to xray service api i'll get an error that the segment is already closed, because the xray sdk patch is trying to trace the put segments api call. if i leave the segment open, i can't send it because its open. feels like a catch 22. at a previous version of the xray sdk library this did actually work.

**Comment by kapilt** [comment]
https://github.com/aws/aws-xray-sdk-python/blob/master/aws_xray_sdk/ext/botocore/patch.py#L34

this should ideally exempt PutTraceSegments for applications doing direct integration

**Comment by awssandra** [comment]
Hi kapilt,

Sorry for the issues! Can you post what versions of AWS SDK and X-Ray SDK you are using? Is there any reason you are using the X-Ray Service APIs directly instead of using the Daemon to send the data?

Typically, we do enable tracing on all AWS SDK calls, so I'm not sure how this has changed in the past. Happy to help you deep-dive in.

**Comment by kapilt** [comment]
because the xray daemon is an installation barrier i don't want my users to have, as this is just a cli (related #51). the sw also runs in lambda where we will detect that and fallback to the lambda xray daeemon. i originally developed the xray integration oct 2018 which looks like xray sdk 2.2.0 .. its an easy albeit  hacky work around to monkey patch the botocore monkey patch to exempt put trace segments.. but again a trace segment can't be sent unless its closed, so it would be nice to see this upstream on the existing xray api call exemptions in botocore patching. if you want a bisect on xray sdk versions where this stopped working lmk.

**Comment by kapilt** [comment]
one minor annonyance on the work around, i have to replace the entire patch module because they are currently setup with the function shadowing the module name in the package __init__, such that the module can't be referenced directly from outside of the codebase. i'll see if i can get a pr put together (xray direct emitter, white listing put telemetry api call).

**Comment by shengxil** [comment]
Hi kapilt, thanks for raising the issue and filing the PR. The PR is merged. However as you said, the ultimate solution is to support non-daemon emitter. We are tracking it in backlog and closing this issue for now. Please feel free to file more PRs anytime.
