### ISSUE TITLE
Support for pymysql

### ISSUE THREAD

**Issue by anil-grexit** [aws/aws-xray-sdk-python#214]
Would you please consider adding support for https://github.com/PyMySQL/PyMySQL as a quite popular client library for MySQL DB.

**Comment by srprash** [comment]
Hi @anil-grexit 
Thanks for raising this request. We would be happy to take this in our backlog. We also appreciate any pull requests or contribution to our SDKs.

Thanks.

**Comment by anil-grexit** [comment]
Hi @srprash I have just created a draft pull request. I have tested this myself using the local version of x-ray daemon. Still tests are remaining, will mark it ready for review when I have a chance. Let me know if you have some feedback.

**Comment by anil-grexit** [comment]
Hey @srprash the PR is ready for review now. Thanks

**Comment by srprash** [comment]
@anil-grexit 
Awesome! Thanks for contributing. I'll take a look shortly.

**Comment by srprash** [comment]
Hi @anil-grexit 
This issue has been resolved in the [v2.5.0](https://github.com/aws/aws-xray-sdk-python/releases/tag/2.5.0) release.

Thanks!

**Comment by anil-grexit** [comment]
Thanks @srprash . My team will be really happy to see RDS traces.
