### ISSUE TITLE
asyncio.Task.current_task PendingDeprecation warning

### ISSUE THREAD

**Issue by Amertz08** [aws/aws-xray-sdk-python#216]
Getting a lot of `PendingDeprecation` warnings in the logs.

/usr/local/lib/python3.7/site-packages/aws_xray_sdk/core/async_context.py:64: PendingDeprecationWarning: Task.current_task() is deprecated, use asyncio.current_task() instead

Should be an easy fix.

**Comment by bhautikpip** [comment]
Hi @Amertz08,

Thanks for pointing out this issue. We would love to review PR if you want to contribute!

**Comment by Amertz08** [comment]
Of course. Seems easy enough!

**Comment by srprash** [comment]
The fix has been released in v2.6.0. Please see [Changelog](https://github.com/aws/aws-xray-sdk-python/blob/master/CHANGELOG.rst#260)
