### ISSUE TITLE
Sending segment batch failed with: NoCredentialProviders: no valid provider

### ISSUE THREAD

**Issue by Hassan1175** [aws/aws-xray-sdk-python#236]
I am running daemon locally for my Django project to get traces.
I have configured the credentials in environment variables  and ~/.aws/credentials file as well. But still facing that issue. Can anybody please help me in figuring out issue.
The error which I am facing is

Sending segment batch failed with: NoCredentialProviders: no valid provider

**Comment by awssandra** [comment]
Hi Hassan1175,

Would you mind to re-opening this in the aws/aws-xray-daemon Github issues queue? This is a daemon issue, and we're happy to help sort it out. 

When you open the other issue, can you include your daemon startup logs in full? Also, in which environment are you running the daemon, and which version are you running?

Thanks!
Sandra

**Comment by Hassan1175** [comment]
Done
