### ISSUE TITLE
Flask request traces missing method, path, IP

### ISSUE THREAD

**Issue by revmischa** [aws/aws-xray-sdk-python#238]
I'm using the Flask middleware:
```python
    patcher.patch(("requests", "boto3"))  # xray tracing for external requests
    xray_recorder.configure(service="hr")
    XRayMiddleware(app, xray_recorder)
```

SQLAlchemy queries are properly annotated, traces are created. But they are missing method, URL, client IP.

<img width="1496" alt="Screen Shot 2020-07-24 at 11 45 30 PM" src="https://user-images.githubusercontent.com/245131/88433955-cbf2c780-ce07-11ea-9cb6-3c0a0ae0b481.png">

**Comment by srprash** [comment]
Hi @revmischa 
I guess these traces are for the incoming requests to your Flask server. How are you querying the SQLAlchemy db? Can you provide an extended code snippet which shows the middleware instrumentation as well as the SQLAlchemy component?

**Comment by revmischa** [comment]
They are incoming web flask requests yes. SQLAlchemy isn't the issue, the HTTP request metadata like path and method not appearing is the issue.

**Comment by srprash** [comment]
Okay. If it is possible to put breakpoints and debug your code, can you try to debug at [this](https://github.com/aws/aws-xray-sdk-python/blob/master/aws_xray_sdk/ext/flask/middleware.py#L31) line and see if `req` contains the URL, METHOD, and CLIENT_IP fields? Also verify if the incoming requests are hitting [these](https://github.com/aws/aws-xray-sdk-python/blob/master/aws_xray_sdk/ext/flask/middleware.py#L58-#L60) lines of code.

A couple of more questions. What is the environment your application is running in? Are the requests directly hitting your Flask server or are they getting re-routed by a load balancer or something?

**Comment by revmischa** [comment]
I'm using lambda proxy with https://www.serverless.com/plugins/serverless-wsgi

**Comment by srprash** [comment]
I see. Can you verify that you've enabled active tracing on the API Gateway stage as well as the Lambda function? For API GW, you can enable X-Ray tracing by checking the "Enable X-Ray Tracing" checkbox under "Logs/Tracing" tab of your API stage. Similarly for the lambda function, enable "Active Tracing" under the "Monitoring Tools" section.

**Comment by revmischa** [comment]
Ah, it wasn't enabled on the APIGW. Didn't know about that one. Thanks!
