### ISSUE TITLE
Deprecate support for python 2.7 and 3.4 in the next major version

### ISSUE THREAD

**Issue by srprash** [aws/aws-xray-sdk-python#255]
Python [2.7](https://www.python.org/doc/sunset-python-2/)(the last of python2) and [3.4](https://www.python.org/downloads/release/python-3410/#:~:text=10%20was%20released%20on%20March,new%20releases%20will%20be%20made.) have reached their end-of-life and are no longer supported.

The SDK should deprecate the support for these versions in the 3.0.0 release. FYI, the OpenTelemetry for Python [supports python 3.5 and above](https://github.com/open-telemetry/opentelemetry-python/blob/master/opentelemetry-api/setup.cfg#L37).

**Comment by michael-k** [comment]
Python 3.5 has reached its EOL in September 2020: https://www.python.org/dev/peps/pep-0478/

OpenTelemetry for Python dropped support for Python 3.5 in https://github.com/open-telemetry/opentelemetry-python/commit/d21793d1249ee6e41180dc9a33755c6dcc0e94a1.

**Comment by michael-k** [comment]
Python 3.6 has reached its EOL in December 2021: https://peps.python.org/pep-0494/

OpenTelemetry for Python is preparing to drop support for Python 3.6, see https://github.com/open-telemetry/opentelemetry-python/pull/2763.

**Comment by michael-k** [comment]
@jj22ee has dropped support for Python < 3.7 in 2.12, see eg. eaffcc801138fcf44d540dbf500299285a453158.  But there's still work to do:
- The [classifiers](https://github.com/aws/aws-xray-sdk-python/blob/c57d293198251e276988440400140ac247c24606/setup.py#L31-L36) still suggest support for Python 2.7 and 3.4–3.6.
- [install_requires](https://github.com/aws/aws-xray-sdk-python/blob/c57d293198251e276988440400140ac247c24606/setup.py#L44-L49) includes dependencies for Python 2.7
- There's no python_requires to prevent pip from installing 2.12 on Python < 3.7.
- … (only had a rough look so far)
