### ISSUE TITLE
Add ability to run disabled

### ISSUE THREAD

**Issue by thehesiod** [aws/aws-xray-sdk-python#26]
datadog tracing (https://github.com/DataDog/dd-trace-py) has the ability to disable tracing via a `enabled` parameter to their `configure` method (https://github.com/DataDog/dd-trace-py/blob/master/ddtrace/tracer.py#L82).  This is really useful so one can control the behavior of tracing via an environment variable for example without having to change code, allowing for local and prod behaviors.  I suggest a similar mechanism for xray

**Comment by thehesiod** [comment]
if I have any free time I'll try working on a PR, however guidance and recommendations are welcome

**Comment by haotianw465** [comment]
We have some improvement plan on this matter internally but right now we cannot provide more details. I will leave this open to gather feedback from broader audience. But a PR is always welcome for a quick improvement. 

Also keep in mind that it doesn't matter whether you disable tracing or not if the application is not the starting point on your microserivces, as any X-Ray integrated service (apps instrumented with X-Ray SDK, AWS Lambda etc) respects the sampling decision passed from upstream. So if you have a full call path all integrated you will just need to change your frontend sampling to `rate=0` and `fixed_target=0` to completely disable X-Ray tracing.

**Comment by thehesiod** [comment]
ah, perhaps if `enabled=False` it just does that?

**Comment by haotianw465** [comment]
Yes you can definitely do that with a PR. That doesn't conflict with any of our internal work. Please stay tuned. Thanks.

**Comment by jaysonsantos** [comment]
Hey there, this feature is quite important especially if you are running tests as TargetPoller and RulePoller's threads will never die if there is no agent running.
The dirty fix i made was a fixture to kill those threads after pytest finishes testing.
```python
@pytest.yield_fixture('session', autouse=True)
def fix_xray_threads():
    # TODO: This should be removed after https://github.com/aws/aws-xray-sdk-python/issues/26 is solved
    yield
    import ctypes
    import threading
    main_thread = threading.main_thread()
    for thread in threading.enumerate():
        if thread.daemon or thread == main_thread:
            continue

        ctypes.pythonapi.PyThreadState_SetAsyncExc(ctypes.c_long(thread.ident), ctypes.py_object(SystemExit))

```

**Comment by thehesiod** [comment]
i forget why we didn't merge my "enabled" param support.

**Comment by jaysonsantos** [comment]
Hi @haotianw465 our app initializes xray in our root module `__init__.py` which would be the first thing imported by the tests and it already starts the two threads. I saw the option to disable the sampling but that would still spin up the threads, no?

**Comment by jaysonsantos** [comment]
Never mind @haotianw465 checking the code again I saw that the threads are initialized when the first segment is sent. If I call configure before the first segment is sent they will never start.
Thank you!

**Comment by chanchiem** [comment]
PR merged into main branch
