### ISSUE TITLE
The SDK only checks environment variables if you pass in a value on configuring

### ISSUE THREAD

**Issue by ckuhl** [aws/aws-xray-sdk-python#262]
On configuring the recorder, it will only pull in the environment variable `AWS_XRAY_DAEMON_ADDRESS` if you also pass in some value for `daemon_address` into `AWSXRayRecorder.configure` method (see [line 152 of `recorder.py`](https://github.com/aws/aws-xray-sdk-python/blob/3c1218ebaa167bf02813644f1ad896fd85249281/aws_xray_sdk/core/recorder.py#L152-L153)).

Perhaps I am simply misunderstanding how the configuration should work, but when I compared this behaviour with the way the SDK worked in JavaScript, that implementation [always checked the environment variable](https://github.com/aws/aws-xray-sdk-node/blob/695f0498d/packages/core/lib/daemon_config.js#L61-L62) on setup.

**Comment by srprash** [comment]
Hi @ckuhl 
When the `AWSXRayRecorder` is initialized, it initializes the [`UDPEmitter`](https://github.com/aws/aws-xray-sdk-python/blob/master/aws_xray_sdk/core/recorder.py#L68) as well. Within the [initialization of `UDPEmitter`](https://github.com/aws/aws-xray-sdk-python/blob/master/aws_xray_sdk/core/emitters/udp_emitter.py#L26), [`DaemonConfig` initialization](https://github.com/aws/aws-xray-sdk-python/blob/3c1218ebaa167bf02813644f1ad896fd85249281/aws_xray_sdk/core/emitters/udp_emitter.py#L48) checks if the `AWS_XRAY_DAEMON_ADDRESS` environment variable is set or not. If not, the address defaults to 127.0.0.1:2000. All of this happens before the AWSXRayRecorder is configured via the `configure` method, so make sure that your environment variable is set before the importing the xray_recorder. Also, while configuring the daemon address in the recorder, the environment variable has a higher precedence than the value passed in to the `configure` method.

Are you having any issues setting the daemon address in the recorder?  Can you provide a small snippet of how you're importing the xray_recorder and configuring it?
