### ISSUE TITLE
How do I use x-ray for lambdas that use the  public.ecr.aws/lambda/python:3.8 base image?

### ISSUE THREAD

**Issue by hjb417** [aws/aws-xray-sdk-python#265]
Fails for me.

[ERROR] TypeError: 'AsyncAWSXRayRecorder' object is not callable
Traceback (most recent call last):
  File "/var/lang/lib/python3.8/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/var/lang/lib/python3.8/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 702, in _load
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/var/task/app.py", line 5, in <module>
    def handler(event, context):

Below is app.py

from aws_xray_sdk.core import patch_all, xray_recorder
patch_all()

@xray_recorder
def handler(event, context):
    return event

**Comment by bhautikpip** [comment]
Hi @hjb417 ,

Would you be able to provide repro steps and code? It would be good if we can reproduce this issue. I think from the description of the issue it would be hard to understand what is going on when we use python lambda docker image with x-ray.

**Comment by wangzlei** [comment]
Don't need annotation @xray_recorder.
Make sure you have fully installed xray python sdk dependency `aws-xray-sdk` to your docker image folder `/var/rumtime` or `/opt/python` or `/var/task`. The easiest way is adding `aws-xray-sdk` in requirements.txt.

Here is docker file example:
```
FROM public.ecr.aws/lambda/python:3.8
COPY function/lambda_function.py function/requirements.txt ./
RUN python3.8 -m pip install -r requirements.txt
CMD ["lambda_function.lambda_handler"]
```

**Comment by hjb417** [comment]
This is what my docker file looked like

FROM public.ecr.aws/lambda/python:3.8

# Install packages
RUN yum install -y yum-utils
RUN yum groupinstall -y "Development Tools"
RUN yum install -y gcc gcc-c++ krb5-libs krb5-devel unixODBC unixODBC-devel
RUN pip install boto3 aws-xray-sdk
ENV TMP=/tmp

# Copy function code
COPY app.py ${LAMBDA_TASK_ROOT}

# Set the CMD to your handler (could also be done as a parameter override outside of the Dockerfile)
CMD [ "app.handler" ]

**Comment by hjb417** [comment]
It works now. Thx. 
I changed "RUN pip install boto3 aws-xray-sdk" to "RUN python3.8 -m pip install boto3 aws-xray-sdk"

**Comment by awssandra** [comment]
Hi hjb417,

Feel free to reopen for any additional questions.

Thanks!
Sandra
