### ISSUE TITLE
Error when serializing segment causes invalid message to be sent to the daemon

### ISSUE THREAD

**Issue by trossyvormes** [aws/aws-xray-sdk-python#288]
#283 makes `Entity.to_dict` throw an exception in some cases. When `to_dict` throws an exception, `Entity.serialize` returns `None`:

https://github.com/aws/aws-xray-sdk-python/blob/7602447db1b5dbd98fcda804942e86853cb50809/aws_xray_sdk/core/models/entity.py#L264-L265

Anyway, the `None` is put into the message that is sent to the daemon, so the daemon gets `{"format":"json","version":1}\nNone`, which is an invalid message.

https://github.com/aws/aws-xray-sdk-python/blob/7602447db1b5dbd98fcda804942e86853cb50809/aws_xray_sdk/core/emitters/udp_emitter.py#L35-L37

I don't think catching everything and returning `None` in `Entity.serialize` is a good idea. The exception should continue to be raised and the message send request should be aborted.

See also aws/aws-xray-daemon#120.

**Comment by lupengamzn** [comment]
Hey @trossyvormes ,

Thank you for pointing this out

We're fixing the Python serialization issue in [PR](https://github.com/aws/aws-xray-sdk-python/pull/284) and as for the Daemon issue you mentioned, we figured out that this is an issue introduced in the latest release happened last Friday. We'll do a patch release for both Python SDK and Daemon soon.

Sorry for the inconvenience this brought to you.

**Comment by trossyvormes** [comment]
> Hey @trossyvormes ,
> 
> Thank you for pointing this out
> 
> We're fixing the Python serialization issue in [PR](https://github.com/aws/aws-xray-sdk-python/pull/284) and as for the Daemon issue you mentioned, we figured out that this is an issue introduced in the latest release happened last Friday. We'll do a patch release for both Python SDK and Daemon soon.
> 
> Sorry for the inconvenience this brought to you.

Hello Lu. Fixing the serialization error is a band-aid to the real problem which is that `None` is returned by `Entity.serialize` when `to_dict` fails. If there is a new bug in `Entity.to_dict` that raises an exception you will get the same bug again. `Entity.serialize` has to change and not return `None` when `to_dict` fails.

**Comment by lupengamzn** [comment]
@trossyvormes Yes, totally agree that SDK should do the sanity check for this case. Will do a followup PR.

**Comment by lupengamzn** [comment]
Closing this issue as it's addressed in PR #292
