### ISSUE TITLE
pypi doc issue

### ISSUE THREAD

**Issue by thehesiod** [aws/aws-xray-sdk-python#30]
if you compare xray: https://pypi.python.org/pypi/aws-xray-sdk/0.96
to aiohttp: https://pypi.python.org/pypi/aiohttp

You can tell something is broken :)

**Comment by haotianw465** [comment]
You are right. I did some research and PyPI still doesn't render markdown file. I will need to use tool like [Pandoc](http://pandoc.org) to convert the `README.md` file to `.rst` in `setup.py`.

This will be fixed in the next release.

**Comment by haotianw465** [comment]
Released as part of 0.97
