### ISSUE TITLE
Lambda root segment immutability workaround

### ISSUE THREAD

**Issue by andrestone** [aws/aws-xray-sdk-python#304]
Hi!

When using the JS SDK, as a workaround for the Lambda root segment immutability, I was able to manually create segments in my lambda code, referencing the root segment I receive in an SQS message (attributes).

This SDK seems to prohibit using `xray_recorder.begin_segment` to start a segment if being called inside a Lambda (as shown [here](https://github.com/aws/aws-xray-sdk-python/blob/d025f5641496efdc9dfad2b270139c224053885c/aws_xray_sdk/core/lambda_launcher.py#L58)).

Is there a workaround that could be used here or should I use boto / direct API calls?

Thanks.

**Comment by myke2424** [comment]
bump

**Comment by bhautikpip** [comment]
resolving this issue in favor of this https://github.com/aws/aws-xray-sdk-python/issues/308
