### ISSUE TITLE
'import pkg_resources' is slow and impacts cold starts

### ISSUE THREAD

**Issue by prestomation** [aws/aws-xray-sdk-python#305]
There are two locations in the code base that use `from pkg_resources import resource_filename` to get the location of some packaged, static json data.

During some profiling of a ~1.5gb python3.8 lambda function, I discovered that this import alone takes on the order of 250ms and is one of the larger single contributors of cold start in my sample function.

Could we consider some other method for consuming this data?

**Comment by NathanielRN** [comment]
Thanks for bringing this to our attention, @prestomation !

I was able to reproduce the slow behavior of `resource_filename` and found a solution online to make the loading faster. We just merged #306 in hopes of improving the performance, which should go out in the next release.

Let me know if you have any additional questions or comments!

**Comment by heitorlessa** [comment]
Hey @NathanielRN do we have some rough dates on when the next release will be out?

It's been a couple of months since the last release. It'd be awesome to have this Perf improvement out for customers

**Comment by NathanielRN** [comment]
Thanks for the prompt @heitorlessa ! I'll message the team and see if they can cut us a release soon.

**Comment by NathanielRN** [comment]
This should have been released in be4dea2f89e44dd52c68b23e1620b8541947e64b as version `2.9.0`. Closing this issue.
