### ISSUE TITLE
Removing Segment/Subsugment Name invalid characters.

### ISSUE THREAD

**Issue by harveyslash** [aws/aws-xray-sdk-python#31]
When using Mysql with flask sqlalchemy, i get this log: 
```Removing Segment/Subsugment Name invalid characters.```

My SQLALCHEMY URI IS : 

mysql://user:pass@url.something.ap-south-1.rds.amazonaws.com:3306/semiprod?charset=utf8mb4

Even if I remove the ?charset, it seems to be automatically added by sqlalchemy

**Comment by haotianw465** [comment]
Hi, could you share the final subsegment name representing your SQL transaction? We will take a look soon.

**Comment by harveyslash** [comment]
@therealryanbonham's solves it

**Comment by haotianw465** [comment]
Close in favor of https://github.com/aws/aws-xray-sdk-python/issues/36
