### ISSUE TITLE
concurrent asyncio tasks and xray are not working with Lambda

### ISSUE THREAD

**Issue by abivolmv** [aws/aws-xray-sdk-python#310]
Hello,
I am opening this issue on request of @NathanielRN after a discussion with him in https://github.com/aws/aws-xray-sdk-python/issues/203 .

The problem is that when using aioboto3, asyncio (with gather or wait) and xray in Lambda we either get an exception or no subsegments showing calls to S3 or SQS.
Here is the last code snippet from that issue:

```python
import asyncio
from io import BytesIO

import aioboto3
from aws_xray_sdk.core import xray_recorder, patch_all
from aws_xray_sdk.core.async_context import AsyncContext

# here I tried adding your solution (not added when solution to use AsyncContext() is used below)
# xray_recorder.configure(service='repro_xray_issue')  # uncomment this for second solution trial

patch_all()


def lambda_handler(a,b):
    asyncio.run(main())


async def main():
    # here I tried adding your solution (not added when solution to remove AsyncContext() is used above)
    xray_recorder.configure(service='repro_xray_issue', context=AsyncContext())    # comment this for second solution trial
    async with xray_recorder.in_segment_async('my_segment_name') as segment:  # comment this for second solution trial
        filelike1 = BytesIO()
        filelike2 = BytesIO()
        res1, res2 = await asyncio.gather(s3_get(filelike1), s3_get(filelike2))  # .wait() doesn't work either


@xray_recorder.capture_async('s3_get')  # tried with this and without also
async def s3_get(filelike):
    async with aioboto3.Session().client('s3') as s3:
        return await s3.download_fileobj('s3-validation-files-003', 'test.txt', filelike)
```

**Comment by willarmiros** [comment]
Hi @abivolmv,

Thanks for creating this separate issue and posting some reproduction code. We have this as an investigation item in our backend and will follow up when we have bandwidth.

**Comment by NathanielRN** [comment]
Adding some notes I took down during my quick investigation of this issue:

It looks like our `AsyncContextManager` is able to `__aexit__` before the `s3` tasks initiated by `asyncio` finish. Maybe it's not put on the `taskLoop` correctly OR it just finishes faster so that they finish before the other tasks finish creating and ending their sub segments. A reminder that this bug sometimes happens and sometimes does not happen.

I'm referring lines specifically to these lines of the `async_recorder.py` for `AsyncContextManager`:

https://github.com/aws/aws-xray-sdk-python/blob/b5b99b7561eb46c831c5aff07563b7a923d47f41/aws_xray_sdk/core/async_recorder.py#L13-L14

[PEP 484 says](https://www.python.org/dev/peps/pep-0492/) that the __aexit__ function should be returning an "awaitable", but I am not sure if our code is returnning just that.

I managed to avoid the "Traceback Exception" by changing the code like this:

```python
class AsyncSegmentContextManager(SegmentContextManager):
    async def __aenter__(self):
        return self.__enter__()

    async def __aexit__(self, exc_type, exc_val, exc_tb):
        async def nested():
            self.__exit__(exc_type, exc_val, exc_tb)

        task = await asyncio.gather(nested())

        return task
```

The traces show up on X-Ray but they are _sometimes_ blank with no data in them!

This issues requires investigating how `asyncio` works. Specifically, we need to confirm that we "schedule the self.exit task" on the asyncio loop instead of running it immediately (so that the previous async calls have a chance to finish) OR that the task doesn't get pulled off the loop until the previous ones to make calls to S3 run to completion.

**Comment by abivolmv** [comment]
Hello guys,
just wanted to spark some interest in this issue as we have Lambda timing out sometimes (very rarely) but can't see why since Xray won't show much due to the aforementioned issue.

**Comment by abivolmv** [comment]
Thanks for the fix , I will try and see if it works now for me too

**Comment by abivolmv** [comment]
Oh, I have to wait for a new release to pypi. Or how can I test before that ? Also when is the new release going to happen as I see it's not so often.

**Comment by NathanielRN** [comment]
Hey @abivolmv, thanks for your patience! Can you see release 2.10.0 now? https://github.com/aws/aws-xray-sdk-python/releases/tag/2.10.0

Let us know if it works for you 🙂

**Comment by abivolmv** [comment]
Hi @NathanielRN appreciate your and your colleagues' effort on this.
I tried the new version and I can see the segments in a proper way in xray console when I test locally or in Lambda. 
But I notice it creates a new segment that is not tied to the Lambda one. 

So when I have the use case API GW -> Lambda -> S3 I have 2 traces , which beats the purpose of xray as I cannot see the start and end of the same workflow in the same trace. Maybe I am not integrating correctly the solution ? Here is how it looks like in Lambda:

```python
import asyncio
from io import BytesIO
import aioboto3
from aws_xray_sdk.core import xray_recorder, patch_all
from aws_xray_sdk.core.async_context import AsyncContext

patch_all()
aio_session = aioboto3.Session()


def lambda_handler(a, b):
    asyncio.run(main())


async def main():
    # here I tried adding your solution (not added when solution to remove AsyncContext() is used above)
    xray_recorder.configure(context=AsyncContext())
    async with xray_recorder.in_segment_async('my_segment_name') as segment:
        filelike1 = BytesIO()
        filelike2 = BytesIO()
        res1, res2, res3, res4 = await asyncio.gather(s3_get(filelike1), s3_get(filelike2))


@xray_recorder.capture_async('s3_get')
async def s3_get(filelike):
    async with aio_session.client('s3') as s3:
        return await s3.download_fileobj('s3-tst-bmw-eve-digitalbrochure-validation-files-003', '.versions.txt', filelike)
```

**Comment by NathanielRN** [comment]
Hi @abivolmv, I believe this may be an issue of propagation. I believe you have to instrument the Lambda Handler to read the incoming X-Ray Tracing header coming in from APIGW and used by Lambda. Otherwise the X-Ray SDK in your Lambda will create its own trace.

See more:
https://docs.aws.amazon.com/xray/latest/devguide/xray-concepts.html#xray-concepts-tracingheader

**Comment by abivolmv** [comment]
@NathanielRN this, propagation, happens automatically when I don't use 

```python
xray_recorder.configure(context=AsyncContext())
    async with xray_recorder.in_segment_async('my_segment_name') as segment:
```

Something happens here that detaches the API incoming trace from Lambda custom trace.
We can see that the trace is reaching the Lambda handler in the other parallel trace :

![image](https://user-images.githubusercontent.com/39116856/180964037-442dec88-978f-4dd4-8739-78f0064697c1.png)

I ended up doing this, though it feels counter-intuitive, it shows one full trace: 

```python
trace_id = xray_recorder.get_trace_entity().trace_id
    parent_id = xray_recorder.current_segment().id
    # enable xray to work with async
    # even though Lambda has its own segment we need to create one async segment
    xray_recorder.configure(context=AsyncContext())
    async with xray_recorder.in_segment_async('add_brochure', traceid=trace_id, parent_id=parent_id) as segment:
       ...
```

**Comment by NathanielRN** [comment]
Hm yeah I expect `_in_segment_async` to do that automatically. Would you mind filing a new issue with this so we can keep track of it? Otherwise happy that you have a work around and thank you for being willing to share your findings to make this SDK better! 😄

**Comment by abivolmv** [comment]
Unfortunately the workaround above is only working sometimes. I described it more in the new issue.

**Comment by simonjpartridge** [comment]
I managed to make this work with the following:

Use the `async_xray_traced` as a decorator on your main async function. e.g the function you call with asyncio.run.


```
import asyncio
import copy
from collections.abc import Callable, Coroutine
from typing import TYPE_CHECKING, Any

from aws_lambda_powertools import Logger
from aws_xray_sdk.core import xray_recorder
from aws_xray_sdk.core.async_context import TaskLocalStorage
from aws_xray_sdk.core.lambda_launcher import LambdaContext as XrayLambdaContext

if TYPE_CHECKING:
    from asyncio.tasks import _TaskCompatibleCoro

LOGGER = Logger(child=True)


def task_factory(
    loop: asyncio.AbstractEventLoop, coro: "_TaskCompatibleCoro[Any]", name: str | None = None
) -> asyncio.Task[Any]:
    """
    This class was taken from aws_xray_sdk.core.async_context, but with the addition of
    `name` parameter to support asyncio.Task creation with a name.
    """
    task = asyncio.Task(coro, loop=loop, name=name)
    if task._source_traceback:  # type: ignore[attr-defined] # pragma: no cover
        del task._source_traceback[-1]  # type: ignore[attr-defined]

    # Share context with new task if possible
    current_task = asyncio.current_task(loop=loop)
    if current_task is not None and hasattr(current_task, "context"):
        if current_task.context.get("entities"):
            # NOTE: (enowell) Because the `AWSXRayRecorder`'s `Context` decides
            # the parent by looking at its `_local.entities`, we must copy the entities
            # for concurrent subsegments. Otherwise, the subsegments would be
            # modifying the same `entities` list and sugsegments would take other
            # subsegments as parents instead of the original `segment`.
            #
            # See more: https://github.com/aws/aws-xray-sdk-python/blob/0f13101e4dba7b5c735371cb922f727b1d9f46d8/aws_xray_sdk/core/context.py#L90-L101
            new_context = copy.copy(current_task.context)
            new_context["entities"] = [item for item in current_task.context["entities"]]
        else:
            new_context = current_task.context  # pragma: no cover
        setattr(task, "context", new_context)

    return task


class AsyncLambdaContext(XrayLambdaContext):
    """
    Largely taken from aws_xray_sdk.core.lambda_launcher.LambdaContext
    removed the options to set loops and task factories optionally because we always want to do this
    """

    def __init__(
        self,
        *args: Any,
        **kwargs: dict[str, Any],
    ) -> None:
        super().__init__(*args, **kwargs)
        self._loop = asyncio.get_event_loop()

        self._loop.set_task_factory(task_factory)

        self._local = TaskLocalStorage(loop=self._loop)

    def clear_trace_entities(self) -> None:
        """
        Clear all trace_entities stored in the task local context.
        """
        if self._local is not None:  # pragma: no cover
            self._local.clear()


def async_xray_traced[**P, T](func: Callable[P, Coroutine[Any, Any, T]]) -> Callable[P, Coroutine[Any, Any, T]]:
    """
    Decorator that configures X-Ray for async Lambda functions.

    This decorator temporarily switches the X-Ray context to AsyncLambdaContext
    for the duration of the decorated function execution, then restores the
    original context.

    It should be used once at the entry point to the async functions to enable async tracing.
    e.g you should decorate the function you call with asyncio.run() or similar.
    """

    async def wrapper(*args: P.args, **kwargs: P.kwargs) -> T:
        original_context = xray_recorder.context
        # for tracing to work in async functions we need to use this async lambda context
        xray_recorder.configure(context=AsyncLambdaContext())
        # Set the trace entity to the original context's trace entity
        # This ensures that the subsegment created by the decorator is a child of the original segment
        xray_recorder.set_trace_entity(original_context.get_trace_entity())  # type: ignore[no-untyped-call] # type stubs don't know about this method

        try:
            async with xray_recorder.in_subsegment_async("async: " + func.__name__):  # type: ignore[attr-defined] # type stubs don't know about this method
                a = await func(*args, **kwargs)
                return a
        finally:
            # Restore the original non-async context after the function execution
            xray_recorder.configure(context=original_context)

    return wrapper
```
