### ISSUE TITLE
Support for Snowflake Connector

### ISSUE THREAD

**Issue by njdub** [aws/aws-xray-sdk-python#328]
Snowflake is Cloud-based data warehousing service for structured and semi-structured data (9# position according to https://db-engines.com/en/ranking/relational+dbms)

Would you please consider adding support for https://pypi.org/project/snowflake-connector-python/

**Comment by willarmiros** [comment]
Hi @njdub,

We are not prioritizing adding new instrumentation support to this SDK at this time, but I would recommend opening this request in the OpenTelemetry Python repo: https://github.com/open-telemetry/opentelemetry-python-contrib

X-Ray has first class support for Otel python through the AWS Distro for OpenTelemetry: https://aws-otel.github.io/docs/getting-started/python-sdk

**Comment by njdub** [comment]
@willarmiros Got it, Thank you! 
I've created request in https://github.com/open-telemetry/opentelemetry-python-contrib/issues/948
