### ISSUE TITLE
xray displaying mysql+pymysql connection string with password in the UI

### ISSUE THREAD

**Issue by marcolivierbouch** [aws/aws-xray-sdk-python#335]
Hi,

We have an issue while using xray and the methode patch_all. It is diplaying our credentials in the UI. Is there any missing scrambling or we are not using the library correctly?

We simply added this to our code :
```
from aws_xray_sdk.core import patch_all
patch_all()
```

![image](https://user-images.githubusercontent.com/29548847/167203992-8d2fbd6d-78ce-4fea-92d7-ea2affd2e699.png)

Our setup:
1. Python 3.9
2. AWS Lambda
3. xray version: aws-xray-sdk == 2.9.0
4. sqlalchemy version: SQLAlchemy==1.4.35

Let me know if you need more information.

Thanks

**Comment by srprash** [comment]
Hi @marcolivierbouch 
Sorry that you are seeing confidential info about your connection string in X-Ray details. This shouldn't be happening.

Looking at this code snippet in the `sqlalchemy` instrumentation, I see that the SDK does try to strip off the password. I believe this could be happening due to either of these:
1. The parsed url string [here](https://github.com/aws/aws-xray-sdk-python/blob/master/aws_xray_sdk/ext/sqlalchemy/util/decorators.py#L106) doesn't has the `u.password` value set.
2. The url doesn't match [this pattern](https://github.com/aws/aws-xray-sdk-python/blob/master/aws_xray_sdk/ext/sqlalchemy/util/decorators.py#L111) and therefore fails to strip off the password from the url.

Can you give an idea how you're trying to connect to your mysql db and what does the connection string looks like?

**Comment by marcolivierbouch** [comment]
Hi @srprash, 

Thanks for your response!

This is how I create the connection string:
```
from sqlalchemy.engine.url import URL

x = URL.create(
    drivername="mysql+pymysql",
    host=host,
    username="myuser",
    password="mypassword",
    port=3306,
    database="uam",
)
```

The complete code on my side looks like this:
```
def __init__(self, host: str, username: str, password: str):
    self.engine = create_engine(
        URL.create(
            drivername="mysql+pymysql",
            host=host,
            username=username,
            password=password,
            port=3306,
            database="uam"
        )
    )
    Session.configure(bind=self.engine)
```

**Comment by JPLachance** [comment]
Hello @srprash,

Our connection string contains multiple special chars. This is one example of a connection string leaked into AWS X-Ray:
```
SQL: mysql+pymysql://user_username:hx&&4lsd0z&^MG7v$yAF^%3Awr1.PhbfwAL@some.aws.us-east-1.rds.amazonaws.com:3306/database
```

That password is generated by AWS Secrets Manager on a daily basis.

Could it cause the issue?

My poetry.lock:
```
[[package]]
name = "aws-xray-sdk"
version = "2.11.0"
description = "The AWS X-Ray SDK for Python (the SDK) enables Python developers to record and emit information from within their applications to the AWS X-Ray service."
category = "main"
optional = false
python-versions = "*"

[[package]]
name = "aws-lambda-powertools"
version = "2.4.0"
description = "A suite of utilities for AWS Lambda functions to ease adopting best practices such as tracing, structured logging, custom metrics, batching, idempotency, feature flags, and more."
category = "main"
optional = false
python-versions = ">=3.7.4,<4.0.0"
```

And the code:
```PYTHON
from sqlalchemy import create_engine
from sqlalchemy.engine.url import URL
from sqlalchemy.orm import sessionmaker

Session = sessionmaker()

engine = create_engine(
    URL.create(
        drivername="mysql+pymysql",
        host="some.aws.us-east-1.rds.amazonaws.com",
        username="user_username",
        password="hx&&4lsd0z&^MG7v$yAF^%3Awr1.PhbfwAL",
        port=3306,
        database="database",
    )
)

Session.configure(bind=self.engine)
```

I hope this helps!

**Comment by JPLachance** [comment]
Hello again!

So I did change the password for science. The new one is not leaking.

I suspect `#` to cause our issue.

Thanks!

**Comment by JPLachance** [comment]
@jj22ee, was a fix implemented?

As far as I know, `#` is a valid special char in MySQL.

Thanks!
