### ISSUE TITLE
How to discard a trace by manual?

### ISSUE THREAD

**Issue by Liubey** [aws/aws-xray-sdk-python#369]
to set the segment sampled=True?

Cause I want to create new sample strategy with request time threshold, when the request time less than threshold, manual discard the whole trace.

Thanks.

**Comment by carolabadeer** [comment]
Yes, to discard/not sample a trace, you would set its `sampled` property to `False`. There are a few ways to achieve the result you are looking for. 
- To discard/not sample a segment:
    - Directly set `segment.sampled = False`
    - If using the `xray_recorder`, use the begin_segment method and override the default sampling parameter. 
    ```
    segment = xray_recorder.begin_segment('unsampled-segment', sampling=False)
    ```
- To discard/not sample a subsegment:
    - Directly set `subsegment.sampled = False` 
    - If using the `xray_recorder`, use the `begin_subsegment_without_sampling` method to begin an unsampled subsegment.
    ```
    subsegment = xray_recorder.begin_subsegment_without_sampling('unsampled-subsegment')
    ```
Here is an [example unit test that creates an unsampled segment and an unsampled child subsegment](https://github.com/aws/aws-xray-sdk-python/blob/65c7e19563b70d3994d659ef630c86981dadacea/tests/test_recorder.py#L161-L168). Hope this helps!

**Comment by Liubey** [comment]
@carolabadeer Thank you so much~
