### ISSUE TITLE
Documentation for patch_all

### ISSUE THREAD

**Issue by SamStephens** [aws/aws-xray-sdk-python#403]
There is no documentation of what `patch_all` actually does, even though it's included in an example in README.md.

This is particularly important due to https://github.com/aws/aws-xray-sdk-python/issues/100, talking about the potential of surprises from `patch_all`

Does `patch_all` patch from a whitelist of known libraries that can be patched. Does it have some magic generic approach to try and patch all modules?

Looking at [the code](https://github.com/aws/aws-xray-sdk-python/blob/2976b25750d04ebe6dc7d0a3e399444896e82cae/aws_xray_sdk/core/patcher.py#L15C1-L15C19) makes it clear patch_all patches from a whitelist, but it would be good for this to be documented.

Also, users of `patch` have to read code to understand what they can patch with it. Even a short piece of documentation linking into the code would lower the barrier of entry.

**Comment by SamStephens** [comment]
I see it's [described here](https://docs.aws.amazon.com/xray-sdk-for-python/latest/reference/thirdparty.html), but it'd be good if the [API reference](https://docs.aws.amazon.com/xray-sdk-for-python/latest/reference/aws_xray_sdk.core.html#aws_xray_sdk.core.patch_all) linked to that documentation page.

**Comment by carolabadeer** [comment]
Thanks for the feedback @SamStephens! The PR above adds clarification on the patch functions in the API documentation
