### ISSUE TITLE
Patched DB cursor and template may record outside of XRayMiddleware

### ISSUE THREAD

**Issue by okapies** [aws/aws-xray-sdk-python#414]
I installed `XRayMiddleware` and a custom middleware to our Django app that always returns a 503 response to indicate we are under maintenance. It works, but the app begins to output the following errors for every request:

- `"cannot find the current segment/subsegment, please make sure you have a segment open"`
- `"No segment found, cannot begin subsegment template_render."`

It is because `log_response()`, which may trigger X-Ray's record function (`record_subsegment`) in patched `Cursor` to read `User` from DB and `Template` to render stack traces, can be invoked outside of XRayMiddleware contained in `_middleware_chain`:

```python
        response = self._middleware_chain(request)
        ...
        if response.status_code >= 400:
            log_response(
                "%s: %s",
                response.reason_phrase,
                request.path,
                response=response,
                request=request,
            )
```

https://github.com/django/django/blob/32d70b2f55b1f74736fd11bc8efce890ad5fa2f0/django/core/handlers/base.py#L136-L150

It does not happen when the request handler or middleware raises an exception instead of returning an error response directly thanks to [`convert_exception_to_response`](https://github.com/django/django/blob/85ac33591c393f1480d4f23b4daff40119cb6410/django/core/handlers/exception.py#L24) that calls `log_response()` inside the middleware chain. Otherwise, x-ray logs the above unwanted error messages.

## Note
We can suppress logs by setting `_has_been_logged` to `True` on `Response` inside the handler as a workaround.

```python
response._has_been_logged = True
```

**Comment by srprash** [comment]
Hi @okapies
Adding a bit more detail on how the X-Ray SDK works. The `XRayMiddleware` will create a `Segment` for incoming requests to your Django application, to which child `Subsegment`s can be attached for tracing DB calls. But the DB instrumentation cannot know if the call is always within the middleware, and when that happens, the child `Subsegment` has no parent `Segment` to attach to and is discarded (with a log message). 

You can suppress these specific (we call them context-missing) logs from X-Ray by setting the `AWS_XRAY_CONTEXT_MISSING` property to `IGNORE_ERROR` in your Django app configuration. See here for details: https://docs.aws.amazon.com/xray/latest/devguide/xray-sdk-python-configuration.html#xray-sdk-python-middleware-configuration-django

**Comment by okapies** [comment]
Thanks, I missed the `IGNORE_ERROR` setting. I will use it next time.
