### ISSUE TITLE
Fix docstring in Entity.close()

### ISSUE THREAD

**Issue by roger-zhangg** [aws/aws-xray-sdk-python#424]
### Wrong typehints
The docstring for `end_time` in  the following sections seems to be wrong, it should be in `float` but docstring says `int`

https://github.com/aws/aws-xray-sdk-python/blob/692a43995ca9462c5a04c9963931e1f17c8fb42c/aws_xray_sdk/core/models/entity.py#L62-L76

https://github.com/aws/aws-xray-sdk-python/blob/692a43995ca9462c5a04c9963931e1f17c8fb42c/aws_xray_sdk/core/models/subsegment.py#L130-L140

https://github.com/aws/aws-xray-sdk-python/blob/692a43995ca9462c5a04c9963931e1f17c8fb42c/aws_xray_sdk/core/context.py#L43-L57

https://github.com/aws/aws-xray-sdk-python/blob/692a43995ca9462c5a04c9963931e1f17c8fb42c/aws_xray_sdk/core/context.py#L73-L88

### Correct typehints (on top of wrong ones)
And you can find the following code calling the function above using the correct type hint `float`
https://github.com/aws/aws-xray-sdk-python/blob/692a43995ca9462c5a04c9963931e1f17c8fb42c/aws_xray_sdk/core/recorder.py#L342-L347

https://github.com/aws/aws-xray-sdk-python/blob/692a43995ca9462c5a04c9963931e1f17c8fb42c/aws_xray_sdk/core/recorder.py#L247-L254

## Fix
Verify this issue and Change typehint for `end_time` in Wrong typehints section from `int` to `float`

**Comment by srprash** [comment]
@roger-zhangg Thanks for bringing this to our attention. The docstrings have been fixed.
