### ISSUE TITLE
Unable to get RDS or SQL tracing with psycopg2 plugin

### ISSUE THREAD

**Issue by ohlol** [aws/aws-xray-sdk-python#443]
Hi, I'm trying to use Xray to trace Python Lambdas. I'm currently primarily using boto3 and psycopg2 plugins, but am only seeing segments for the latter. I've tried numerous permutations of the SDK to no avail.

From the documentation, it appears that I should only need to use either an explicit `patch` (including `psycopg2` in the plugin list) or `patch_all`. I do see the successful patch of psycopg2 in my lambda log output. But still no segments representing database queries or traffic.

Is there something I'm missing?

**Comment by srprash** [comment]
Hi @ohlol 
Can you provide a code snippet describing the boto3 and psycopg2 operations you are trying to instrument, and also how you're instrumenting those clients?

It will also be helpful if you can describe the trace you expect to see vs the trace you actually see. Lastly, please provide the application logs and a sample raw trace data if possible. Thank you.

**Comment by ohlol** [comment]
@srprash sorry for the late reply; I had a lot going on. I'm actually not working on this project any more so I'm going to close the issue. Thanks!
