### ISSUE TITLE
Support for OpenTracing naming conventions

### ISSUE THREAD

**Issue by nfisher** [aws/aws-xray-sdk-python#45]
Understand OpenTracing lacks a standardised interface specification however I think it would be a great step forward if the terminology were adopted by this project;

See also; https://github.com/aws/aws-xray-sdk-go/issues/31

And perhaps provide some support for the Flask tracer;

https://github.com/opentracing-contrib/python-flask

**Comment by srprash** [comment]
Hi @nfisher 
We recently announced AWS X-Ray support for OpenTelemetry Python SDK. You can find the documentation [here](https://aws-otel.github.io/docs/getting-started/python-sdk) to get started.

Closing this issue. Please open an issue [here](https://github.com/aws-observability/aws-otel-python) for AWS related stuff with OpenTelemetry Python. Thanks!
