### ISSUE TITLE
Patching instructions may be wrong for specific modules

### ISSUE THREAD

**Issue by StephenGoodall** [aws/aws-xray-sdk-python#71]
I'm not sure if this project looks after the relevant AWS docs page but I followed this page to do the specific module patch (for boto3):
https://docs.aws.amazon.com/xray/latest/devguide/xray-sdk-python-patching.html

Following "Example main.py – patch specific libraries" I wrote this:

```
from aws_xray_sdk.core import patch

libraries = ('boto3')
patch(libraries)
```

Which returned:
```
Exception: modules o, 3, t, b are currently not supported for patching
```

It seems to work if I put it in as:
```
libraries = (['boto3'])
```

So it may be worth changing the docs to show that if you are patching a single module it needs to be in [ ] brackets? I assume it thinks the firs tone is a list of chars, but the second is a single element list? (I'm new to Python - so that may be wrong!)

**Comment by haotianw465** [comment]
Thank you for the feedback. We will fix the doc as soon as possible. Sorry for any inconvenience.
