### ISSUE TITLE
Safer Flask teardown request function

### ISSUE THREAD

**Issue by luyun-aa** [aws/aws-xray-sdk-python#75]
Ref: http://flask.pocoo.org/docs/0.12/reqcontext/#callbacks-and-errors

Flask requests that `teardown_request` function should never fail. The request teardown function implementation in XRay SDK is not robust enough because if before_request is not executed, `context.current_segment` would return None. Any operation on the "None" segment would fail.

**Comment by haotianw465** [comment]
Thank you for your feedback. Just want to clarify do you mean this method https://github.com/aws/aws-xray-sdk-python/blob/master/aws_xray_sdk/ext/flask/middleware.py#L58

**Comment by luyun-aa** [comment]
Ah no, I'm referring to `XRayMiddleware. _handle_exception` (https://github.com/aws/aws-xray-sdk-python/blob/master/aws_xray_sdk/ext/flask/middleware.py#L73), because it's registered to `teardown_request` in `XRayMiddleware.__init__`.

**Comment by haotianw465** [comment]
Thank you for the clarification. We will work on a fix soon.

**Comment by luyun-aa** [comment]
Thanks
