### ISSUE TITLE
Recorder Exception When Beginning Segment

### ISSUE THREAD

**Issue by mjtieman** [aws/aws-xray-sdk-python#81]
`AWSXRayRecorder` is throwing a `TypeError` when creating a new segment. The exception is being thrown because the recorder is calling `should_trace` on the sampler, which starting in 2.0 requires `sample_req`.

Stack trace
```
should_trace() takes exactly 2 arguments (1 given): TypeError
Traceback (most recent call last):
File "/var/task/src/setup_database.py", line 55, in handler
xray_recorder.begin_segment('setup_database.handler')
File "/var/task/aws_xray_sdk/core/recorder.py", line 208, in begin_segment
decision = self._sampler.should_trace()
TypeError: should_trace() takes exactly 2 arguments (1 given)
```

**Comment by haotianw465** [comment]
Thank you for your contribution. I have merged your PR and will prepare a release soon.

**Comment by mjtieman** [comment]
Changes merged
