### ISSUE TITLE
Add SNS Service "Publish" operation to the aws_para_whitelist

### ISSUE THREAD

**Issue by Tankanow** [aws/aws-xray-sdk-python#84]
Currently the SNS publish operation shows up with a minimum set of metadata:
```
"aws": {
    "operation": "Publish",
    "region": "us-east-1",
    "request_id": "a939cee1-7c48-5675-b385-9ae2206dc121"
}
```

This should include at least the known internal AWS resources like `TopicArn` or `TargetArn` and maybe even the `PhoneNumber`.

**Comment by Tankanow** [comment]
I will happily work on this if it's not on the roadmap.

**Comment by haotianw465** [comment]
Hi, `PhoneNumber` is relatively sensitive and recording it by default is probably not a good idea. `TopicArn` on the other hand would be a vey useful information. Feel free to add it to the whitelist by submitting a PR and some unit test.
