### ISSUE TITLE
Test with Django 2.0+

### ISSUE THREAD

**Issue by adamchainz** [aws/aws-xray-sdk-python#85]
Currently the `tox` file installs:

```
django >= 1.10, <2.0
```

Please test with Django 2.0 and 2.1 and confirm compatibility with them. 2.0+ is Python 3 only, perhaps why this restriction was added in the first place?

**Comment by haotianw465** [comment]
Hi, you can see all the reasoning about this restriction here: https://github.com/aws/aws-xray-sdk-python/pull/10. Testing with Django 2.0 is in our backlog. A PR is always welcome.

**Comment by srprash** [comment]
Testing for Django 2.0 and above has been added and released in v2.6.0. Please see [Changelog](https://github.com/aws/aws-xray-sdk-python/blob/master/CHANGELOG.rst#260)
