### ISSUE TITLE
Later streamed subsegments are not in Xray

### ISSUE THREAD

**Issue by otterchurchill** [aws/aws-xray-sdk-python#94]
I have a lambda that is using patch() and active tracing.   Boto3 and the requests library are what is patched.   After the lambda is completed the Xray Timeline says the function is "Pending" with a duration of 2.2 minutes. When removing patch function and removing importing the sdk, the duration is 3.7 minutes(in the Xray console) . When patch(boto3) is included the first 30-40 boto3 client api function calls are in the raw data(StartQueryExecution, GetDatabases).  I put on logging at debug level for the lambd function.  There is a line "streaming subsegments" then "sending:
{
    "format": "json",
    "version": 1
...
    "aws": {
        "operation": "StartQueryExecution",
        "region": "us-west-2",
      . . .
} "

But lets say the 41st client function call  the logs say the same thing("streaming subsegments" "sending:{})  but what is in the "sending: {}" line does not appear in raw data view in Xray.  So at some point in time the later subsegments are not transmitted to the trace.

**Comment by haotianw465** [comment]
Hi, thank you for reporting the issue. Could you provide a snapshot of what a problematic trace timeline look like on X-Ray console so we can take a further look? Please feel free to redact any sensitive information.

Another question is that without instrumenting your lambda function code, how much time do you expect one execution takes?

**Comment by safv12** [comment]
@otterchurchill I'm having the same issue, how did you solve it?

**Comment by bhautikpip** [comment]
Hi @otterchurchill ,

Would you mind providing more information on your case ? By looking at the information on comment looks like lambda function execution is completed before it could close the segment and toggle the `in_progress` flag so that could be the reason there is a pending segment on X-Ray console.

**Comment by safv12** [comment]
Hi @bhautikpip.

I was talking with the support center of AWS and they said that it is a size limit issue.

> I just got an update from the X-ray service team. According to the trace data you provided, there are about 440 subsegments in a single segment `my-segment-name` which denotes the entire lambda function. The maximum size of a segment document can be 64KB as mentioned in the link https://docs.aws.amazon.com/xray/latest/devguide/xray-api-segmentdocuments.html  . This is probably the issue here. 

Thank you.
