### ISSUE TITLE
Issue with using xray with async function

### ISSUE THREAD

**Issue by oba11** [aws/aws-xray-sdk-python#96]
Tried using xray with async function but keep getting this error 

```
Traceback (most recent call last):
  File "app.py", line 333, in <module>
    xray_recorder.end_segment()
  File "/usr/local/lib/python3.6/site-packages/aws_xray_sdk/core/recorder.py", line 206, in end_segment
    if self.current_segment().ready_to_send():
AttributeError: 'NoneType' object has no attribute 'ready_to_send'
```

**PIP**
```
aiobotocore     0.9.4
aws-xray-sdk    1.1
boto3           1.7.58
botocore        1.10.58
```

> N.B: I know latest version of `aws-xray-sdk` is not supported with `aiobotocore`

Thanks

**Comment by haotianw465** [comment]
Hi, could you provide a code snippet of your X-Ray SDK configuration and the part that triggers this error so I can take a further look? Are you running this in AWS Lambda or locally? Is this  a script or a web app? Thanks.

**Comment by haotianw465** [comment]
The particular error is tracked here https://github.com/aws/aws-xray-sdk-python/issues/96. Closing this and please free feel to comment or open a new one if you have problem figuring out why the context doesn't propagate through async functions.
